### PR TITLE
Improved out of bounds read v2

### PR DESCRIPTION
**Pull request by nitro-marky**
Out of bounds read 2 has been changed to accept 3 arguments which are as follows:

    Data: the secret data entered by the user.
    -32: This is the lower memory bound.
    (-32 - (length of input + 1)): This strips any garbage from the end of the secret.

`vscode` has also been added to the `.gitignore` file to stop local logs being pushed.

The way to use this is out-of-bounds-readV2 (data) -32 (calculation from above)
   
` I.E example arg1 arg2 arg3`

**Examples** 🎉 

**aarch64**
`root@cheribsd-morello-purecap:/buildroot # ./out-of-bounds-readV2-aarch64 secret -32 -25
Storing Secret...
The data between indices -32 and -25 is: secret`

**cheri**
`root@cheribsd-morello-purecap:/buildroot # ./out-of-bounds-readV2-cheri secret -32 -25
Storing Secret...
In-address space security exception (core dumped)`

### CODE REVIEW

**Review by mattdean-digicatapult — COMMENTED** [review]
looks good to me. I'd like another approver before we merge as I helped implement this

**Review by n3op2 — COMMENTED** [review]
Could you please copy paste an example's input/output? I mean how you execute binary with arguments? I would assume it's something like:

```sh
morello-example arg1 arg2 arg3

# some output
```

Would be nice to see this in the description

**Comment by nitro-marky** [comment]
> Could you please copy paste an example's input/output? I mean how you execute binary with arguments? I would assume it's something like:
> 
> ```shell
> morello-example arg1 arg2 arg3
> 
> # some output
> ```
> 
Done

**Review by n3op2 — CHANGES_REQUESTED** [review]
I'm sorry, but this is not what I asked.

Can you compile the binary and execute with argument and share the console output e.g.


```sh
~/workspace/cheribuild (master) $ ls -la # THIS IS MY COMMAND
total 384 
drwxr-xr-x  35 PMichelevicius  staff   1120 11 Aug 15:54 .
drwxr-xr-x  45 PMichelevicius  staff   1440  9 Aug 22:16 ..
-rw-r--r--   1 PMichelevicius  staff  16384 11 Aug 15:55 .README.md.swp
-rw-r--r--   1 PMichelevicius  staff     96 25 Jul 19:46 .editorconfig
-rw-r--r--   1 PMichelevicius  staff    123 25 Jul 19:46 .flake8 
# THE ABOVE IS MY COMMANDS OUTPUT
```

Could you please do the same with binary (V2) e.g. execute the binary with arguments and share the output?

**Review by n3op2 — APPROVED** [review]

**Comment by n3op2** [comment]
Thanks for updating

**Review by n3op2 — APPROVED** [review]

**Pull request merged**
